### ISSUE TITLE
CustomCubic world type not fully implemented

### ISSUE THREAD

**Issue by Barteks2x** [OpenCubicChunks/CubicChunks#15]
- [x] Terrain stage - terrain looks differently than vanilla terrain (incorrectly configured noise generator and biome-related code)
- [x] Population stage - mostly unimplemented `/*TODO: list all features to implement*/`
  - [x] Basic biome decorator
    - [x] Make all of that work beyond vanilla heights
  - [x] Biome-specific decorator
  - [x] General populator
- [ ] Structure generation - only caves and ravines are implemented (will it be implemented?)
- [ ] Lava in caves
- [ ] Customization options
  - [x] Advanced terrain shape
  - [x] Basic population options
  - [x] Ore configuration
  - [ ] Block replacer config
  - [ ] Allow setting values directly
  - [ ] Show resulting json config
- [x] Merge Terrain Surface and Structures stages

**Comment by Niko-sk2x** [comment]
Relatively few but complicated to implements things are left to fix, closing this, and reopenign separate issue for each part.

**Comment by Niko-sk2x** [comment]
Opened issues #228 #229 #230 #231 #232 #233 #234 for it.
