### ISSUE TITLE
Add configuration options

### ISSUE THREAD

**Issue by Barteks2x** [OpenCubicChunks/CubicChunks#47]
Currently I identified the following things to configure:
- [x] Max amount of cubes generated per tick (default 49*16)
- [x] Max time spent generating cubes per tick (default 50 milliseconds)
- [x] Vertical cube load distance (options: default=same as horizontal, and values 2-32)
  - [x] Make this option available in video settings and server.properties
- [x] ​(maybe) Max client skylight update depth (default: 64)
- [ ] ~~Enable/disable ChunkGC (when normal chunk unloading is readded)~~ not really possible
- [x] Min/Max world height
  - [x] Dimension height and depth stored in NBT 
  - [ ] Configurable in world type customization options (default value for new dimensions and separate values for dimension IDs)
  - [x] When cubic chunks toggle switch is added - Allow to set default values for new dimensions and separate values for dimension IDs
    (list will be updated as I find more options)

**Comment by sirsavary** [comment]
+ https://github.com/Barteks2x/CubicChunks/issues/50

**Comment by Niko-sk2x** [comment]
All the currently planned options have been added long time ago.
