### ISSUE TITLE
Allow to convert worlds from vanilla

### ISSUE THREAD

**Issue by Barteks2x** [OpenCubicChunks/CubicChunks#49]

**Comment by Barteks2x** [comment]
The best option would probably be releasing a standalone world converter.

**Comment by Cyclonit** [comment]
I don't think this should be a requirement for a beta release. Having it asap would be nice, but it does not keep us from testing, which a beta is all about.

**Comment by Niko-sk2x** [comment]
Closing as particlly functioning standalone converter already exists https://github.com/OpenCubicChunks/CubicChunksConverter
