### ISSUE TITLE
java.lang.RuntimeException: Exception getting cube

### ISSUE THREAD

**Issue by trolls-incorporated** [OpenCubicChunks/CubicChunks#659]
[full crash report](https://pastebin.com/PcgiHkks)

**Comment by CorgiTaco** [comment]
Hi, it seems you've downloaded our 1.17 version which is currently a heavy WIP. We are not taking issues for it at this time as it is susceptible bugs, crashes and currently very incomplete.

**Comment by trolls-incorporated** [comment]
> 
> 
> Hi, it seems you've compiled our 1.17 version which is currently a heavy WIP. We are not taking issues for it at this time as it is susceptible bugs, crashes and currently very incomplete.

what about the other dozens of issues dedicated to the 1.17 version that have been addressed?

**Comment by CursedFlames** [comment]
those are issues made by the devteam (or, like, muzikbike I guess), not users.

**Comment by CorgiTaco** [comment]
These are issues in relation to development. This issue is more of an issue with the usability of the mod.
