### ISSUE TITLE
Vertical view distance applied incorrectly until changed by player

### ISSUE THREAD

**Issue by Cyclonit** [OpenCubicChunks/CubicChunks#69]
![2016-10-15_12 33 43](https://cloud.githubusercontent.com/assets/19320074/19409419/a362cd38-92d3-11e6-87d2-e912ada73b2b.png)
![2016-10-15_12 32 52](https://cloud.githubusercontent.com/assets/19320074/19409420/a36a03dc-92d3-11e6-9df2-2c0d9328b25e.png)

This happens whenever you fly above the ocean. The cubes ~64 blocks underneath are not being rendered. They are loaded, as can be seen by some caves. When flying down, the cubes appear without any generating/loading taking place.

**Comment by Barteks2x** [comment]
I've never seen that issue. What is your vertical view distance?

**Comment by Barteks2x** [comment]
I tested ti and it's most likely that you have vertical view distance set to low value

**Comment by Niko-sk2x** [comment]
Turns out this issue actually was there all the time. For some reason the vertical view distance set in options isn't applied until the player changes it and defaults to (most likely) 3.

**Comment by Niko-sk2x** [comment]
Should be fixed in 143a90e60ec7d08e8f28ab66070c4a7d3f019de6
